<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoanProductsSeeder extends Seeder
{
    public function run(): void
    {
        $loanProducts = [
            [
                'bank_id' => 1,
                'name' => 'CRDB Home Loan',
                'description' => 'Affordable home financing solution with flexible repayment terms',
                'interest_rate' => 14.50,
                'min_tenure_months' => 12,
                'max_tenure_months' => 300,
                'min_amount' => 10000000,
                'max_amount' => 500000000,
                'processing_fee_percentage' => 1.5,
                'requirements' => 'Valid ID, Proof of income, Property valuation, Title deed',
                'features' => 'Up to 90% financing, Flexible repayment, Low interest rates',
                'is_active' => true,
            ],
            [
                'bank_id' => 1,
                'name' => 'CRDB Mortgage Plus',
                'description' => 'Premium mortgage product for high-value properties',
                'interest_rate' => 13.00,
                'min_tenure_months' => 24,
                'max_tenure_months' => 360,
                'min_amount' => 50000000,
                'max_amount' => 1000000000,
                'processing_fee_percentage' => 1.0,
                'requirements' => 'Valid ID, Bank statements (6 months), Property documents, Collateral',
                'features' => 'Competitive rates, Up to 85% LTV, Grace period available',
                'is_active' => true,
            ],
            [
                'bank_id' => 2,
                'name' => 'NMB Nyumba Yangu',
                'description' => 'Your dream home financing made easy',
                'interest_rate' => 15.00,
                'min_tenure_months' => 12,
                'max_tenure_months' => 240,
                'min_amount' => 5000000,
                'max_amount' => 300000000,
                'processing_fee_percentage' => 2.0,
                'requirements' => 'NIDA, Payslips (3 months), Property valuation report',
                'features' => 'Quick approval, Flexible terms, No hidden charges',
                'is_active' => true,
            ],
            [
                'bank_id' => 2,
                'name' => 'NMB Property Finance',
                'description' => 'Comprehensive property financing for individuals and businesses',
                'interest_rate' => 14.00,
                'min_tenure_months' => 24,
                'max_tenure_months' => 300,
                'min_amount' => 20000000,
                'max_amount' => 800000000,
                'processing_fee_percentage' => 1.5,
                'requirements' => 'Business plan (for commercial), Financial statements, Title deed, Insurance',
                'features' => 'Up to 80% financing, Tailored solutions, Dedicated relationship manager',
                'is_active' => true,
            ],
            [
                'bank_id' => 3,
                'name' => 'Stanbic Home Advantage',
                'description' => 'Competitive home loan with attractive rates',
                'interest_rate' => 13.50,
                'min_tenure_months' => 12,
                'max_tenure_months' => 360,
                'min_amount' => 15000000,
                'max_amount' => 600000000,
                'processing_fee_percentage' => 1.2,
                'requirements' => 'ID verification, Income proof, Property documents, Credit check',
                'features' => 'Low interest rates, Flexible repayment, Free property valuation',
                'is_active' => true,
            ],
            [
                'bank_id' => 4,
                'name' => 'SCB Mortgage Solution',
                'description' => 'International standard mortgage financing',
                'interest_rate' => 12.50,
                'min_tenure_months' => 24,
                'max_tenure_months' => 300,
                'min_amount' => 30000000,
                'max_amount' => 1500000000,
                'processing_fee_percentage' => 1.0,
                'requirements' => 'Valid passport/ID, Bank statements (6 months), Property valuation, Legal documents',
                'features' => 'Premium rates, Global expertise, Personalized service',
                'is_active' => true,
            ],
            [
                'bank_id' => 5,
                'name' => 'Exim Property Loan',
                'description' => 'Specialized financing for property acquisition',
                'interest_rate' => 15.50,
                'min_tenure_months' => 12,
                'max_tenure_months' => 180,
                'min_amount' => 10000000,
                'max_amount' => 400000000,
                'processing_fee_percentage' => 2.0,
                'requirements' => 'NIDA/Passport, Employment letter, Property documentation',
                'features' => 'Fast processing, Competitive rates, Flexible terms',
                'is_active' => true,
            ],
            [
                'bank_id' => 6,
                'name' => 'BOA Home Finance',
                'description' => 'Pan-African mortgage solution',
                'interest_rate' => 14.00,
                'min_tenure_months' => 24,
                'max_tenure_months' => 240,
                'min_amount' => 20000000,
                'max_amount' => 500000000,
                'processing_fee_percentage' => 1.5,
                'requirements' => 'Valid ID, Salary slips, Property title, Bank statements',
                'features' => 'Regional expertise, Competitive pricing, Quick turnaround',
                'is_active' => true,
            ],
            [
                'bank_id' => 7,
                'name' => 'Absa Home Loan',
                'description' => 'Trusted home financing from Absa',
                'interest_rate' => 13.75,
                'min_tenure_months' => 12,
                'max_tenure_months' => 300,
                'min_amount' => 15000000,
                'max_amount' => 700000000,
                'processing_fee_percentage' => 1.3,
                'requirements' => 'ID, Proof of income, Property valuation, Credit history',
                'features' => 'Trusted brand, Flexible options, Expert advice',
                'is_active' => true,
            ],
            [
                'bank_id' => 8,
                'name' => 'Azania Nyumba Loan',
                'description' => 'Local bank home financing solution',
                'interest_rate' => 16.00,
                'min_tenure_months' => 12,
                'max_tenure_months' => 200,
                'min_amount' => 5000000,
                'max_amount' => 250000000,
                'processing_fee_percentage' => 2.5,
                'requirements' => 'NIDA, Employment details, Property documents',
                'features' => 'Local understanding, Personalized service, Quick decisions',
                'is_active' => true,
            ],
        ];

        foreach ($loanProducts as $product) {
            DB::table('loan_products')->insert(array_merge($product, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
