<?php

namespace Database\Seeders;

use App\Models\Material;
use Illuminate\Database\Seeder;

class MaterialSeeder extends Seeder
{
    public function run(): void
    {
        $materials = [
            [
                'name' => 'Premium Steel Rebar 12mm',
                'description' => 'High-quality steel reinforcement bar for concrete construction. Grade 60, 12mm diameter.',
                'price' => 45.50,
                'sku' => 'REB-12-001',
                'category' => 'Steel & Metal',
                'brand' => 'SteelMaster',
                'image_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
                'stock_quantity' => 500,
                'unit' => 'meter',
                'specifications' => ['diameter' => '12mm', 'grade' => '60', 'length' => '12m'],
                'is_featured' => true,
                'is_available' => true,
                'discount_percentage' => 0,
                'supplier_name' => 'SteelMaster Industries',
            ],
            [
                'name' => 'Concrete Mix C25/30',
                'description' => 'Ready-mix concrete with 25MPa strength. Perfect for foundations and structural elements.',
                'price' => 120.00,
                'sku' => 'CON-C25-001',
                'category' => 'Concrete',
                'brand' => 'BuildRight',
                'image_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
                'stock_quantity' => 100,
                'unit' => 'cubic_meter',
                'specifications' => ['strength' => '25MPa', 'slump' => '100mm', 'aggregate' => '20mm'],
                'is_featured' => true,
                'is_available' => true,
                'discount_percentage' => 10,
                'supplier_name' => 'BuildRight Concrete',
            ],
            [
                'name' => 'Cement Portland Type I',
                'description' => 'High-quality Portland cement for general construction purposes. 50kg bags.',
                'price' => 8.50,
                'sku' => 'CEM-PT1-001',
                'category' => 'Cement',
                'brand' => 'CementPro',
                'image_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
                'stock_quantity' => 1000,
                'unit' => 'bag',
                'specifications' => ['type' => 'Portland I', 'weight' => '50kg', 'strength' => '42.5N'],
                'is_featured' => false,
                'is_available' => true,
                'discount_percentage' => 0,
                'supplier_name' => 'CementPro Ltd',
            ],
            [
                'name' => 'Red Clay Bricks',
                'description' => 'Traditional red clay bricks for masonry construction. Standard size 215x102.5x65mm.',
                'price' => 0.85,
                'sku' => 'BRK-RED-001',
                'category' => 'Bricks & Blocks',
                'brand' => 'ClayWorks',
                'image_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
                'stock_quantity' => 10000,
                'unit' => 'piece',
                'specifications' => ['size' => '215x102.5x65mm', 'type' => 'Clay', 'color' => 'Red'],
                'is_featured' => true,
                'is_available' => true,
                'discount_percentage' => 5,
                'supplier_name' => 'ClayWorks Bricks',
            ],
            [
                'name' => 'Steel I-Beam 200x100mm',
                'description' => 'Structural steel I-beam for load-bearing applications. Grade S275.',
                'price' => 85.00,
                'sku' => 'IBE-200-001',
                'category' => 'Steel & Metal',
                'brand' => 'SteelMaster',
                'image_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
                'stock_quantity' => 50,
                'unit' => 'meter',
                'specifications' => ['size' => '200x100mm', 'grade' => 'S275', 'length' => '12m'],
                'is_featured' => false,
                'is_available' => true,
                'discount_percentage' => 0,
                'supplier_name' => 'SteelMaster Industries',
            ],
            [
                'name' => 'Roofing Sheets Galvanized',
                'description' => 'Corrugated galvanized steel roofing sheets. 0.5mm thickness, 1m width.',
                'price' => 25.00,
                'sku' => 'ROF-GAL-001',
                'category' => 'Roofing',
                'brand' => 'RoofPro',
                'image_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
                'stock_quantity' => 200,
                'unit' => 'sheet',
                'specifications' => ['thickness' => '0.5mm', 'width' => '1m', 'length' => '3m'],
                'is_featured' => true,
                'is_available' => true,
                'discount_percentage' => 0,
                'supplier_name' => 'RoofPro Materials',
            ],
            [
                'name' => 'PVC Pipes 110mm',
                'description' => 'Heavy-duty PVC pipes for drainage and water supply. 110mm diameter.',
                'price' => 15.50,
                'sku' => 'PVC-110-001',
                'category' => 'Plumbing',
                'brand' => 'PipeMaster',
                'image_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
                'stock_quantity' => 300,
                'unit' => 'meter',
                'specifications' => ['diameter' => '110mm', 'pressure' => '10bar', 'length' => '6m'],
                'is_featured' => false,
                'is_available' => true,
                'discount_percentage' => 0,
                'supplier_name' => 'PipeMaster Ltd',
            ],
            [
                'name' => 'Electrical Cable 2.5mm²',
                'description' => 'Copper electrical cable for internal wiring. 2.5mm² cross-section.',
                'price' => 3.20,
                'sku' => 'CAB-2.5-001',
                'category' => 'Electrical',
                'brand' => 'ElectroMax',
                'image_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=300&fit=crop',
                'stock_quantity' => 1000,
                'unit' => 'meter',
                'specifications' => ['cross_section' => '2.5mm²', 'voltage' => '450/750V', 'conductor' => 'Copper'],
                'is_featured' => true,
                'is_available' => true,
                'discount_percentage' => 0,
                'supplier_name' => 'ElectroMax Supplies',
            ],
        ];

        foreach ($materials as $material) {
            Material::create($material);
        }
    }
}