<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $properties = [
            [
                'title' => 'Modern Family Home',
                'price' => 450000,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'sqft' => 2500,
                'address' => '123 Main Street, Downtown',
                'image_url' => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&h=300&fit=crop',
                'tag' => 'New Listing',
                'status' => 'Active',
                'agent_name' => 'John Smith',
                'mls_id' => 'MLS123456',
                'property_type' => 'Residential',
                'description' => 'Beautiful modern family home with spacious rooms and updated kitchen.',
                'is_featured' => true,
            ],
            [
                'title' => 'Luxury Condo',
                'price' => 320000,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'sqft' => 1200,
                'address' => '456 Oak Avenue, Uptown',
                'image_url' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=300&fit=crop',
                'tag' => 'Price Reduced',
                'status' => 'Active',
                'agent_name' => 'Sarah Johnson',
                'mls_id' => 'MLS789012',
                'property_type' => 'Condo',
                'description' => 'Luxury condo with city views and modern amenities.',
                'is_featured' => true,
            ],
            [
                'title' => 'Historic Victorian',
                'price' => 680000,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'sqft' => 3200,
                'address' => '789 Heritage Lane, Historic District',
                'image_url' => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=400&h=300&fit=crop',
                'tag' => 'Featured',
                'status' => 'Active',
                'agent_name' => 'Mike Wilson',
                'mls_id' => 'MLS345678',
                'property_type' => 'Residential',
                'description' => 'Stunning historic Victorian home with original features and modern updates.',
                'is_featured' => true,
            ],
            [
                'title' => 'Modern Apartment',
                'price' => 280000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'sqft' => 800,
                'address' => '321 Pine Street, City Center',
                'image_url' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
                'tag' => 'Great Value',
                'status' => 'Active',
                'agent_name' => 'Lisa Brown',
                'mls_id' => 'MLS901234',
                'property_type' => 'Apartment',
                'description' => 'Modern apartment in the heart of the city with great amenities.',
                'is_featured' => true,
            ],
            [
                'title' => 'Suburban Family House',
                'price' => 520000,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'sqft' => 1800,
                'address' => '456 Elm Street, Suburbs',
                'image_url' => 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&h=300&fit=crop',
                'tag' => 'New Listing',
                'status' => 'Active',
                'agent_name' => 'David Lee',
                'mls_id' => 'MLS567890',
                'property_type' => 'Residential',
                'description' => 'Perfect family home in quiet suburban neighborhood.',
                'is_featured' => true,
            ],
            [
                'title' => 'Downtown Loft',
                'price' => 380000,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'sqft' => 1400,
                'address' => '789 Urban Plaza, Downtown',
                'image_url' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
                'tag' => 'Featured',
                'status' => 'Active',
                'agent_name' => 'Emma Davis',
                'mls_id' => 'MLS234567',
                'property_type' => 'Loft',
                'description' => 'Stylish downtown loft with exposed brick and modern finishes.',
                'is_featured' => true,
            ],
            [
                'title' => 'Beach House',
                'price' => 750000,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'sqft' => 2800,
                'address' => '123 Ocean Drive, Beachfront',
                'image_url' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=300&fit=crop',
                'tag' => 'Featured',
                'status' => 'Active',
                'agent_name' => 'Robert Taylor',
                'mls_id' => 'MLS890123',
                'property_type' => 'Residential',
                'description' => 'Stunning beach house with ocean views and private beach access.',
                'is_featured' => true,
            ],
            [
                'title' => 'Mountain Cabin',
                'price' => 420000,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'sqft' => 1600,
                'address' => '456 Forest Road, Mountains',
                'image_url' => 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop',
                'tag' => 'Great Value',
                'status' => 'Active',
                'agent_name' => 'Jennifer White',
                'mls_id' => 'MLS456789',
                'property_type' => 'Cabin',
                'description' => 'Cozy mountain cabin perfect for weekend getaways.',
                'is_featured' => true,
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}