<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => "Sarah Property Seller",
                'email' => "seller@example.com",
                'email_verified_at' => null,
                'password' => '$2y$12$L/nl27e7SwkCCjPT8D.J9.Fdk8gaHkNwMzjtJFVyVYyLokDgKkyxG',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => "2025-10-17 12:03:47",
                'updated_at' => "2025-10-17 12:03:47",
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'user_type' => "seller",
                'business_type' => null,
                'nida_document' => null,
                'passport_document' => null,
                'business_license' => null,
                'certificate_of_incorporation' => null,
                'tax_clearance_certificate' => null,
                'memorandum_of_association' => null,
                'articles_of_association' => null,
                'board_resolution' => null,
                'proof_of_address' => null,
                'bank_statement' => null,
                'kyc_status' => "pending",
                'kyc_notes' => null,
            ],
            [
                'name' => "Mike Materials Supplier",
                'email' => "supplier@example.com",
                'email_verified_at' => null,
                'password' => '$2y$12$l/pIOySTdBYQ9dsW3EFGo.5QHAKLQ4YGprKLAAuYL.jmgOt9vB1Je',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => "2025-10-17 12:03:47",
                'updated_at' => "2025-10-17 12:03:47",
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'user_type' => "supplier",
                'business_type' => null,
                'nida_document' => null,
                'passport_document' => null,
                'business_license' => null,
                'certificate_of_incorporation' => null,
                'tax_clearance_certificate' => null,
                'memorandum_of_association' => null,
                'articles_of_association' => null,
                'board_resolution' => null,
                'proof_of_address' => null,
                'bank_statement' => null,
                'kyc_status' => "pending",
                'kyc_notes' => null,
            ],
            [
                'name' => "Lisa Property Landlord",
                'email' => "landlord@example.com",
                'email_verified_at' => null,
                'password' => '$2y$12$TGwtSOncocT08pcm0dsauO8Mda.8QK3RwZZ3OMMAl0kOIXOr1g1Hq',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => "2025-10-17 12:03:47",
                'updated_at' => "2025-10-17 12:03:47",
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'user_type' => "landlord",
                'business_type' => null,
                'nida_document' => null,
                'passport_document' => null,
                'business_license' => null,
                'certificate_of_incorporation' => null,
                'tax_clearance_certificate' => null,
                'memorandum_of_association' => null,
                'articles_of_association' => null,
                'board_resolution' => null,
                'proof_of_address' => null,
                'bank_statement' => null,
                'kyc_status' => "pending",
                'kyc_notes' => null,
            ],
            [
                'name' => "Savanna System Manager",
                'email' => "savanna@example.com",
                'email_verified_at' => "2025-10-17 12:08:36",
                'password' => '$2y$12$28b7UKQT4dTxs11a1FcdO.SW4QQJyyjhsRQFevPDlKWtkKrR4tfE6',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => "2025-10-17 12:03:47",
                'updated_at' => "2025-10-19 14:53:59",
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'user_type' => "savanna",
                'business_type' => null,
                'nida_document' => null,
                'passport_document' => null,
                'business_license' => null,
                'certificate_of_incorporation' => null,
                'tax_clearance_certificate' => null,
                'memorandum_of_association' => null,
                'articles_of_association' => null,
                'board_resolution' => null,
                'proof_of_address' => null,
                'bank_statement' => null,
                'kyc_status' => "pending",
                'kyc_notes' => null,
            ],
            [
                'name' => "Roary Willis",
                'email' => "nibygykini@mailinator.com",
                'email_verified_at' => null,
                'password' => '$2y$12$QUzQ8CMvHHlWssxG/MTcBe0cZm07JXEQ5LEFpZYbdrMOUoc3O32I6',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => "2025-10-20 07:24:12",
                'updated_at' => "2025-10-20 07:24:12",
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'user_type' => "supplier",
                'business_type' => null,
                'nida_document' => null,
                'passport_document' => null,
                'business_license' => null,
                'certificate_of_incorporation' => null,
                'tax_clearance_certificate' => null,
                'memorandum_of_association' => null,
                'articles_of_association' => null,
                'board_resolution' => null,
                'proof_of_address' => null,
                'bank_statement' => null,
                'kyc_status' => "pending",
                'kyc_notes' => null,
            ],
            [
                'name' => "Andrew Mashamba",
                'email' => "andrew.s.mashamba@gmail.com",
                'email_verified_at' => null,
                'password' => '$2y$12$XuE.aKRiJt0HA/ImKzLeB.T8pG8opRMzwHdFL.19bEQ9Bj80AY0Gu',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => "2025-10-22 11:25:01",
                'updated_at' => "2025-10-22 08:25:43",
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'user_type' => "savanna",
                'business_type' => null,
                'nida_document' => null,
                'passport_document' => null,
                'business_license' => null,
                'certificate_of_incorporation' => null,
                'tax_clearance_certificate' => null,
                'memorandum_of_association' => null,
                'articles_of_association' => null,
                'board_resolution' => null,
                'proof_of_address' => null,
                'bank_statement' => null,
                'kyc_status' => "pending",
                'kyc_notes' => null,
            ],
            [
                'name' => "Grace Hendrix",
                'email' => "kulebepuc@mailinator.com",
                'email_verified_at' => null,
                'password' => '$2y$12$K2BPAGvPBI5ooi9YEubkzOqijJdu.tgImpoINgg6eYpf9wfXIBrde',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => "2025-10-22 08:42:00",
                'updated_at' => "2025-10-22 08:42:00",
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'user_type' => "agent",
                'business_type' => null,
                'nida_document' => null,
                'passport_document' => null,
                'business_license' => null,
                'certificate_of_incorporation' => null,
                'tax_clearance_certificate' => null,
                'memorandum_of_association' => null,
                'articles_of_association' => null,
                'board_resolution' => null,
                'proof_of_address' => null,
                'bank_statement' => null,
                'kyc_status' => "pending",
                'kyc_notes' => null,
            ],
            
        ]);

    }
}
